Repository devwithpug/RandHand-Chat, pull requests merged in 2021-08, with the labels that each got.

#25 feature: 유사도 계산 알고리즘 구현, 가중치 및 전처리 과정 추가 [#17]
  .gitignore
  handDetection/model/main.py
  handDetection/static_image/analysis.ipynb
  handDetection/static_image/analysis2.ipynb
  handDetection/static_image/dataSets/mediapipe.csv
  handDetection/static_image/mediapipe_start.py
Labels: 🐸Object Detection, 😃기능 구현

#31 안드로이드 Gilde 사용시 오류 및 패키지 정리
  android/RandHandChat/.idea/deploymentTargetDropDown.xml
  android/RandHandChat/.idea/gradle.xml
  android/RandHandChat/app/build.gradle
  android/RandHandChat/app/src/main/AndroidManifest.xml
  android/RandHandChat/app/src/main/java/com/kyonggi/randhand_chat/Adapter/BlockedUserAdapter.kt
  android/RandHandChat/app/src/main/java/com/kyonggi/randhand_chat/Adapter/UserAdapter.kt
  android/RandHandChat/app/src/main/java/com/kyonggi/randhand_chat/Domain/User/Client.kt
  android/RandHandChat/app/src/main/java/com/kyonggi/randhand_chat/Domain/User/ResponseUser.kt
  android/RandHandChat/app/src/main/java/com/kyonggi/randhand_chat/Domain/User/UserInfo.kt
  android/RandHandChat/app/src/main/java/com/kyonggi/randhand_chat/Fragments/FriendFragment.kt
  android/RandHandChat/app/src/main/java/com/kyonggi/randhand_chat/Fragments/SettingFragment.kt
  android/RandHandChat/app/src/main/java/com/kyonggi/randhand_chat/Fragments/UserActivity/BlockedFriendActivity.kt
  android/RandHandChat/app/src/main/java/com/kyonggi/randhand_chat/Fragments/UserActivity/EditProfileActivity.kt
  android/RandHandChat/app/src/main/java/com/kyonggi/randhand_chat/Fragments/UserActivity/ProfileActivity.kt
  android/RandHandChat/app/src/main/java/com/kyonggi/randhand_chat/Fragments/UserProfileFragment.kt
  android/RandHandChat/app/src/main/java/com/kyonggi/randhand_chat/LoginActivity.kt
  android/RandHandChat/app/src/main/java/com/kyonggi/randhand_chat/MainActivity.kt
  android/RandHandChat/app/src/main/java/com/kyonggi/randhand_chat/Retrofit/IRetrofit/IRetrofitUser.kt
  android/RandHandChat/app/src/main/java/com/kyonggi/randhand_chat/Retrofit/ServiceURL.kt
  android/RandHandChat/app/src/main/res/layout-v21/activity_blocked_friend.xml
  android/RandHandChat/app/src/main/res/layout/activity_blocked_friend.xml
  android/RandHandChat/app/src/main/res/layout/activity_chat.xml
  android/RandHandChat/gradle/wrapper/gradle-wrapper.properties
Labels: 👿버그, 👀안드로이드

#36 feature: 안드로이드 채팅관련 앱 내부 저장 구현 [#34]
  android/RandHandChat/.idea/deploymentTargetDropDown.xml
  android/RandHandChat/.idea/libraries/Gradle__androidx_arch_core_core_runtime_2_0_0_aar.xml
  android/RandHandChat/.idea/libraries/Gradle__androidx_arch_core_core_runtime_2_0_1_aar.xml
  android/RandHandChat/.idea/libraries/Gradle__androidx_multidex_multidex_2_0_1_aar.xml
  android/RandHandChat/.idea/libraries/Gradle__androidx_multidex_multidex_instrumentation_2_0_0_aar.xml
  android/RandHandChat/.idea/libraries/Gradle__androidx_room_room_common_2_2_6.xml
  android/RandHandChat/.idea/libraries/Gradle__androidx_room_room_ktx_2_2_6_aar.xml
  android/RandHandChat/.idea/libraries/Gradle__androidx_room_room_runtime_2_2_6_aar.xml
  android/RandHandChat/.idea/libraries/Gradle__androidx_sqlite_sqlite_2_0_1_aar.xml
  android/RandHandChat/.idea/libraries/Gradle__androidx_sqlite_sqlite_framework_2_0_1_aar.xml
  android/RandHandChat/.idea/libraries/Gradle__org_jetbrains_kotlinx_kotlinx_coroutines_android_1_3_0.xml
  android/RandHandChat/.idea/libraries/Gradle__org_jetbrains_kotlinx_kotlinx_coroutines_core_1_3_0.xml
  android/RandHandChat/.idea/misc.xml
  android/RandHandChat/app/build.gradle
  android/RandHandChat/app/src/main/AndroidManifest.xml
  android/RandHandChat/app/src/main/java/com/kyonggi/randhand_chat/Adapter/ChatRoomAdapter.kt
  android/RandHandChat/app/src/main/java/com/kyonggi/randhand_chat/Adapter/MessageAdapter.kt
  android/RandHandChat/app/src/main/java/com/kyonggi/randhand_chat/Database/ChatRoomDAO.kt
  android/RandHandChat/app/src/main/java/com/kyonggi/randhand_chat/Database/ChatRoomDatabase.kt
  android/RandHandChat/app/src/main/java/com/kyonggi/randhand_chat/Database/ChatRooms.kt
  android/RandHandChat/app/src/main/java/com/kyonggi/randhand_chat/Database/Converters.kt
  android/RandHandChat/app/src/main/java/com/kyonggi/randhand_chat/Domain/Chat/ChatRoom.kt
  android/RandHandChat/app/src/main/java/com/kyonggi/randhand_chat/Domain/Message/Message.kt
  android/RandHandChat/app/src/main/java/com/kyonggi/randhand_chat/Fragments/ChatListFragment.kt
  android/RandHandChat/app/src/main/java/com/kyonggi/randhand_chat/Fragments/ChatsActivity/ChatActivity.kt
  android/RandHandChat/app/src/main/res/layout/apply_message.xml
  android/RandHandChat/app/src/main/res/layout/list_chats.xml
  android/RandHandChat/app/src/main/res/layout/my_message.xml
Labels: 😃기능 구현, 👍개선 사항, 👀안드로이드

#37 feature: 실제 sessionId를 통하여 웹소켓 및 syncMessage 받기
  android/RandHandChat/.idea/deploymentTargetDropDown.xml
  android/RandHandChat/.idea/gradle.xml
  android/RandHandChat/.idea/libraries/Gradle__androidx_multidex_multidex_instrumentation_2_0_0_aar.xml
  android/RandHandChat/.idea/misc.xml
  android/RandHandChat/app/build.gradle
  android/RandHandChat/app/src/main/AndroidManifest.xml
  android/RandHandChat/app/src/main/java/com/kyonggi/randhand_chat/Adapter/ChatRoomAdapter.kt
  android/RandHandChat/app/src/main/java/com/kyonggi/randhand_chat/Adapter/MessageAdapter.kt
  android/RandHandChat/app/src/main/java/com/kyonggi/randhand_chat/Database/ChatRoomDAO.kt
  android/RandHandChat/app/src/main/java/com/kyonggi/randhand_chat/Database/ChatRoomTable.kt
  android/RandHandChat/app/src/main/java/com/kyonggi/randhand_chat/Database/Converters.kt
  android/RandHandChat/app/src/main/java/com/kyonggi/randhand_chat/Database/MessageDAO.kt
  android/RandHandChat/app/src/main/java/com/kyonggi/randhand_chat/Database/MessageTable.kt
  android/RandHandChat/app/src/main/java/com/kyonggi/randhand_chat/Domain/Chat/ChatInfo.kt
  android/RandHandChat/app/src/main/java/com/kyonggi/randhand_chat/Domain/Message/MessageInfo.kt
  android/RandHandChat/app/src/main/java/com/kyonggi/randhand_chat/Domain/Message/SyncInfo.kt
  android/RandHandChat/app/src/main/java/com/kyonggi/randhand_chat/Fragments/ChatListFragment.kt
  android/RandHandChat/app/src/main/java/com/kyonggi/randhand_chat/Fragments/ChatsActivity/ChatActivity.kt
  android/RandHandChat/app/src/main/java/com/kyonggi/randhand_chat/Retrofit/IRetrofit/IRetrofitChat.kt
  android/RandHandChat/app/src/main/java/com/kyonggi/randhand_chat/Retrofit/IRetrofit/IRetrofitUser.kt
Labels: 😃기능 구현, 👀안드로이드

#44 안드로이드 MediaPipe와 연결 및 서버와 통신[#43]
  android/RandHandChat/.idea/deploymentTargetDropDown.xml
  android/RandHandChat/.idea/libraries/Gradle__androidx_arch_core_core_runtime_2_0_1_aar.xml
  android/RandHandChat/.idea/libraries/Gradle__androidx_camera_camera_camera2_1_0_1_aar.xml
  android/RandHandChat/.idea/libraries/Gradle__androidx_camera_camera_core_1_0_1_aar.xml
  android/RandHandChat/.idea/libraries/Gradle__androidx_camera_camera_lifecycle_1_0_1_aar.xml
  android/RandHandChat/.idea/libraries/Gradle__androidx_camera_camera_view_1_0_0_alpha28_aar.xml
  android/RandHandChat/.idea/libraries/Gradle__androidx_lifecycle_lifecycle_livedata_2_0_0_aar.xml
  android/RandHandChat/.idea/libraries/Gradle__androidx_lifecycle_lifecycle_livedata_2_1_0_aar.xml
  android/RandHandChat/.idea/libraries/Gradle__com_google_auto_value_auto_value_1_8_1.xml
  android/RandHandChat/.idea/libraries/Gradle__com_google_auto_value_auto_value_annotations_1_8_1.xml
  android/RandHandChat/.idea/libraries/Gradle__com_google_code_findbugs_jsr305_2_0_1.xml
  android/RandHandChat/.idea/libraries/Gradle__com_google_code_findbugs_jsr305_3_0_2.xml
  android/RandHandChat/.idea/libraries/Gradle__com_google_errorprone_error_prone_annotations_2_2_0.xml
  android/RandHandChat/.idea/libraries/Gradle__com_google_flogger_flogger_0_6.xml
  android/RandHandChat/.idea/libraries/Gradle__com_google_flogger_flogger_system_backend_0_6.xml
  android/RandHandChat/.idea/libraries/Gradle__com_google_guava_failureaccess_1_0_1.xml
  android/RandHandChat/.idea/libraries/Gradle__com_google_guava_guava_27_0_1_android.xml
  android/RandHandChat/.idea/libraries/Gradle__com_google_guava_listenablefuture_9999_0_empty_to_avoid_conflict_with_guava.xml
  android/RandHandChat/.idea/libraries/Gradle__com_google_j2objc_j2objc_annotations_1_1.xml
  android/RandHandChat/.idea/libraries/Gradle__com_google_mediapipe_hands_0_8_7_alpha_1_aar.xml
  android/RandHandChat/.idea/libraries/Gradle__com_google_mediapipe_solution_core_0_8_7_alpha_1_aar.xml
  android/RandHandChat/.idea/libraries/Gradle__com_google_protobuf_protobuf_java_3_11_4.xml
  android/RandHandChat/.idea/libraries/Gradle__org_checkerframework_checker_compat_qual_2_5_3.xml
  android/RandHandChat/.idea/libraries/Gradle__org_codehaus_mojo_animal_sniffer_annotations_1_17.xml
  android/RandHandChat/.idea/misc.xml
  android/RandHandChat/app/build.gradle
  android/RandHandChat/app/src/main/AndroidManifest.xml
  android/RandHandChat/app/src/main/java/com/kyonggi/randhand_chat/Fragments/ChatListFragment.kt
  android/RandHandChat/app/src/main/java/com/kyonggi/randhand_chat/Fragments/ChatsActivity/ChatActivity.kt
  android/RandHandChat/app/src/main/java/com/kyonggi/randhand_chat/MediaPipe/HandsResultImageView.kt
  android/RandHandChat/app/src/main/java/com/kyonggi/randhand_chat/MediaPipe/MediaPipeActivity.kt
  android/RandHandChat/app/src/main/java/com/kyonggi/randhand_chat/MediaPipe/SendRequestActivity.kt
  android/RandHandChat/app/src/main/java/com/kyonggi/randhand_chat/Retrofit/GestureServiceURL.kt
  android/RandHandChat/app/src/main/java/com/kyonggi/randhand_chat/Retrofit/IRetrofit/IRetrofitGesture.kt
  android/RandHandChat/app/src/main/res/drawable/round_button_mediapipe.xml
  android/RandHandChat/app/src/main/res/layout/activity_media_pipe.xml
  android/RandHandChat/app/src/main/res/layout/activity_send_request.xml
  android/RandHandChat/app/src/main/res/layout/apply_image_message.xml
  android/RandHandChat/app/src/main/res/layout/my_image_message.xml
Labels: 😃기능 구현, 👀안드로이드

#45 안드로이드 웹소켓 접속 및 채팅방 나가기 구현[#43]
  android/RandHandChat/.idea/deploymentTargetDropDown.xml
  android/RandHandChat/app/build.gradle
  android/RandHandChat/app/src/main/java/com/kyonggi/randhand_chat/Adapter/ChatRoomAdapter.kt
  android/RandHandChat/app/src/main/java/com/kyonggi/randhand_chat/Fragments/ChatListFragment.kt
  android/RandHandChat/app/src/main/java/com/kyonggi/randhand_chat/Fragments/ChatsActivity/ChatActivity.kt
  android/RandHandChat/app/src/main/java/com/kyonggi/randhand_chat/MediaPipe/MediaPipeActivity.kt
  android/RandHandChat/app/src/main/java/com/kyonggi/randhand_chat/MediaPipe/SendRequestActivity.kt
  android/RandHandChat/app/src/main/java/com/kyonggi/randhand_chat/ProgressActivity.kt
  android/RandHandChat/app/src/main/java/com/kyonggi/randhand_chat/Retrofit/IRetrofit/IRetrofitChat.kt
  android/RandHandChat/app/src/main/java/com/kyonggi/randhand_chat/Retrofit/IRetrofit/IRetrofitGesture.kt
  android/RandHandChat/app/src/main/res/layout/activity_media_pipe.xml
  android/RandHandChat/app/src/main/res/layout/activity_send_request.xml
Labels: 😃기능 구현, 👀안드로이드

#46 안드로이드 카메라 캡쳐 이미지 회전 fix
  android/RandHandChat/.idea/deploymentTargetDropDown.xml
  android/RandHandChat/.idea/misc.xml
  android/RandHandChat/app/src/main/java/com/kyonggi/randhand_chat/Adapter/MessageAdapter.kt
  android/RandHandChat/app/src/main/java/com/kyonggi/randhand_chat/Fragments/ChatsActivity/ChatActivity.kt
  android/RandHandChat/app/src/main/java/com/kyonggi/randhand_chat/Fragments/FriendFragment.kt
  android/RandHandChat/app/src/main/java/com/kyonggi/randhand_chat/Fragments/UserActivity/ProfileActivity.kt
  android/RandHandChat/app/src/main/java/com/kyonggi/randhand_chat/MediaPipe/MediaPipeActivity.kt
  android/RandHandChat/app/src/main/java/com/kyonggi/randhand_chat/MediaPipe/SendRequestActivity.kt
  android/RandHandChat/app/src/main/java/com/kyonggi/randhand_chat/ProgressActivity.kt
  android/RandHandChat/app/src/main/java/com/kyonggi/randhand_chat/SplashActivity.kt
  android/RandHandChat/app/src/main/res/layout/activity_blocked_friend.xml
  android/RandHandChat/app/src/main/res/layout/activity_edit_profile.xml
  android/RandHandChat/app/src/main/res/layout/activity_profile.xml
  android/RandHandChat/app/src/main/res/menu/main_toolbar_menu.xml
  android/RandHandChat/app/src/main/res/menu/message_context_menu.xml
  android/RandHandChat/app/src/main/res/menu/message_toolbar_menu.xml
Labels: 👍개선 사항, 👀안드로이드
