Repository devwithpug/RandHand-Chat, pull requests merged in 2021-07, with the labels that each got.

#14 feature : plot 이미지 범례 표시 & 여러가지 scaler 적용 [#4], [#7]
  mediaPipe/analysis.ipynb
  mediaPipe/coordinate/mediapipe.csv
  mediaPipe/mediapipe_test.py
Labels: 🐸Object Detection, 👍개선 사항

#15 feature: 앱 실행시 Splash 화면 구현 [#5]
  android/RandHandChat/app/build.gradle
  android/RandHandChat/app/src/main/AndroidManifest.xml
  android/RandHandChat/app/src/main/java/com/kyonggi/randhand_chat/SplashActivity.kt
  android/RandHandChat/app/src/main/res/drawable-v23/splash_background.xml
  android/RandHandChat/app/src/main/res/drawable-v24/hand_icon.png
  android/RandHandChat/app/src/main/res/drawable/gradient.xml
  android/RandHandChat/app/src/main/res/drawable/splash_background.xml
  android/RandHandChat/app/src/main/res/layout/activity_splash.xml
  android/RandHandChat/app/src/main/res/mipmap-hdpi/app_icon.png
  android/RandHandChat/app/src/main/res/mipmap-hdpi/app_icon_round.png
  android/RandHandChat/app/src/main/res/mipmap-mdpi/app_icon.png
  android/RandHandChat/app/src/main/res/mipmap-mdpi/app_icon_round.png
  android/RandHandChat/app/src/main/res/mipmap-xhdpi/app_icon.png
  android/RandHandChat/app/src/main/res/mipmap-xhdpi/app_icon_round.png
  android/RandHandChat/app/src/main/res/mipmap-xxhdpi/app_icon.png
  android/RandHandChat/app/src/main/res/mipmap-xxhdpi/app_icon_round.png
  android/RandHandChat/app/src/main/res/mipmap-xxxhdpi/app_icon.png
  android/RandHandChat/app/src/main/res/mipmap-xxxhdpi/app_icon_round.png
  android/RandHandChat/app/src/main/res/values-v21/themes.xml
  android/RandHandChat/app/src/main/res/values/colors.xml
  android/RandHandChat/app/src/main/res/values/strings.xml
  android/RandHandChat/app/src/main/res/values/themes.xml
  android/RandHandChat/app/src/main/res/xml/activity_splash_scene.xml
Labels: 👀안드로이드, 😃기능 구현

#22 feature: 채팅관련 메시지 xml 추가[#11]
  android/RandHandChat/app/build.gradle
  android/RandHandChat/app/src/main/AndroidManifest.xml
  android/RandHandChat/app/src/main/java/com/kyonggi/randhand_chat/Adapter/UserAdapter.kt
  android/RandHandChat/app/src/main/java/com/kyonggi/randhand_chat/ChatActivity.kt
  android/RandHandChat/app/src/main/java/com/kyonggi/randhand_chat/Fragments/ChatFragment.kt
  android/RandHandChat/app/src/main/java/com/kyonggi/randhand_chat/Fragments/FriendFragment.kt
  android/RandHandChat/app/src/main/java/com/kyonggi/randhand_chat/Fragments/SettingFragment.kt
  android/RandHandChat/app/src/main/java/com/kyonggi/randhand_chat/Fragments/UserProfileFragment.kt
  android/RandHandChat/app/src/main/java/com/kyonggi/randhand_chat/LoginActivity.kt
  android/RandHandChat/app/src/main/java/com/kyonggi/randhand_chat/MainActivity.kt
  android/RandHandChat/app/src/main/java/com/kyonggi/randhand_chat/SplashActivity.kt
  android/RandHandChat/app/src/main/res/drawable/apply_message.xml
  android/RandHandChat/app/src/main/res/drawable/chat_filled.png
  android/RandHandChat/app/src/main/res/drawable/chat_notfilled.png
  android/RandHandChat/app/src/main/res/drawable/more_filled.png
  android/RandHandChat/app/src/main/res/drawable/more_notfilled.png
  android/RandHandChat/app/src/main/res/drawable/my_message.xml
  android/RandHandChat/app/src/main/res/drawable/user_filled.png
  android/RandHandChat/app/src/main/res/drawable/user_notfilled.png
  android/RandHandChat/app/src/main/res/layout/activity_chat.xml
  android/RandHandChat/app/src/main/res/layout/activity_login.xml
  android/RandHandChat/app/src/main/res/layout/activity_main.xml
  android/RandHandChat/app/src/main/res/layout/apply_message.xml
  android/RandHandChat/app/src/main/res/layout/fragment_chattings.xml
  android/RandHandChat/app/src/main/res/layout/fragment_friends.xml
  android/RandHandChat/app/src/main/res/layout/fragment_profile.xml
  android/RandHandChat/app/src/main/res/layout/fragment_settings.xml
  android/RandHandChat/app/src/main/res/layout/list_friends.xml
  android/RandHandChat/app/src/main/res/layout/my_message.xml
  android/RandHandChat/app/src/main/res/values/themes.xml
Labels: 👀안드로이드
