Repository devwithpug/RandHand-Chat, pull requests merged in 2021-09, with the labels that each got.

#48 README (알고리즘 설명 및 정리) 완료
  handDetection/README.md
  handDetection/img/1.png
  handDetection/img/2.png
  handDetection/img/3.png
  handDetection/img/4.png
  handDetection/model/main.py
  handDetection/model/main3.py
  handDetection/static_image/analysis.ipynb
  handDetection/static_image/analysis2.ipynb
Labels: 📄문서화, 🐸Object Detection

#49 docs: Android README Upload
  README.md
  android/안드로이드 정리/Android Debug SHA Key.md
  android/안드로이드 정리/Android EventBus 사용하기.md
  android/안드로이드 정리/Android Glide 사용하기.md
  android/안드로이드 정리/Android Retrofit 사용하기.md
  handDetection/README.md
Labels: 📄문서화, 👀안드로이드

#50 안드로이드 매칭관련 추가 및 간단한 수정
  android/RandHandChat/.idea/deploymentTargetDropDown.xml
  android/RandHandChat/.idea/libraries/Gradle__androidx_multidex_multidex_2_0_1_aar.xml
  android/RandHandChat/.idea/misc.xml
  android/RandHandChat/app/src/main/java/com/kyonggi/randhand_chat/Fragments/FriendFragment.kt
  android/RandHandChat/app/src/main/java/com/kyonggi/randhand_chat/LoginActivity.kt
  android/RandHandChat/app/src/main/java/com/kyonggi/randhand_chat/ProgressActivity.kt
  android/RandHandChat/app/src/main/java/com/kyonggi/randhand_chat/Retrofit/IRetrofit/IRetrofitGesture.kt
  android/RandHandChat/app/src/main/res/layout/activity_login.xml
  android/RandHandChat/app/src/main/res/layout/activity_progress.xml
  android/RandHandChat/app/src/main/res/layout/fragment_friends.xml
  android/RandHandChat/app/src/main/res/layout/fragment_settings.xml
Labels: 👿버그, 😃기능 구현, 👀안드로이드
